<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="bin\Debug\net8.0\Map\fighting\fishMap.txt" />
  </ItemGroup>

  <ItemGroup>

    <None Update="Map\fighting\FightingMenu.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <None Update="Map\fighting\fishMap.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <None Update="Map\Fishing\clouds.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

    <None Update="Map\Fishing\complete.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

    <None Update="Map\Fishing\rain.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

    <None Update="Map\Fishing\waves.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Map\map.txt">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
    <None Update="Map\map_right.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Map\map_start.txt">

      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Map\map_up.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Map\menu.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
